-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.airport
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    location character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT api_common_airport_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.auth_user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    CONSTRAINT auth_user_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.auth_user_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.auth_user_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.authtoken_token
(
    key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT authtoken_token_pkey PRIMARY KEY (key),
    CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.booking
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    booking_date timestamp with time zone NOT NULL,
    client_id integer NOT NULL,
    booking_type_id bigint NOT NULL,
    flight_id bigint NOT NULL,
    CONSTRAINT api_common_booking_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.booking_type
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    type character varying(30) COLLATE pg_catalog."default" NOT NULL,
    price double precision,
    CONSTRAINT api_common_bookingtype_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cancellation_request
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    request_date timestamp with time zone NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    reason text COLLATE pg_catalog."default",
    client_id integer NOT NULL,
    flight_id bigint NOT NULL,
    CONSTRAINT cancellation_request_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.client
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_staff boolean NOT NULL,
    is_superuser boolean NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT client_pkey PRIMARY KEY (id),
    CONSTRAINT client_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.client_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    client_id integer NOT NULL,
    group_id bigint NOT NULL,
    CONSTRAINT api_common_clientgroups_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.client_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    client_id integer NOT NULL,
    permission_id bigint NOT NULL,
    CONSTRAINT api_common_clientpermissions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE TABLE IF NOT EXISTS public.flight
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    flight_number character varying(10) COLLATE pg_catalog."default" NOT NULL,
    departure timestamp with time zone NOT NULL,
    arrival timestamp with time zone NOT NULL,
    plane_id bigint NOT NULL,
    track_destination_id bigint NOT NULL,
    track_origin_id bigint NOT NULL,
    CONSTRAINT api_common_flight_pkey PRIMARY KEY (id),
    CONSTRAINT api_common_flight_flight_number_key UNIQUE (flight_number)
);

CREATE TABLE IF NOT EXISTS public."group"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT api_common_group_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payment_gateway
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    gateway_response text COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    processed_at timestamp with time zone NOT NULL,
    transaction_id bigint NOT NULL,
    CONSTRAINT payment_gateway_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.permission
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT api_common_permission_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.plane
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    second_class_capacity integer NOT NULL,
    first_class_capacity integer NOT NULL,
    CONSTRAINT api_common_plane_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.staff
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_staff boolean NOT NULL,
    is_superuser boolean NOT NULL,
    staff_type_id bigint NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT staff_pkey PRIMARY KEY (id),
    CONSTRAINT staff_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.staff_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id bigint NOT NULL,
    staff_id integer NOT NULL,
    CONSTRAINT api_common_staffgroups_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.staff_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    permission_id bigint NOT NULL,
    staff_id integer NOT NULL,
    CONSTRAINT api_common_staffpermissions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.staff_type
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT api_common_stafftype_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.track
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    track_number character varying(10) COLLATE pg_catalog."default" NOT NULL,
    length integer NOT NULL,
    airport_id bigint NOT NULL,
    CONSTRAINT api_common_track_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.transaction
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    amount double precision NOT NULL,
    transaction_date timestamp with time zone NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    booking_id bigint,
    client_id integer NOT NULL,
    CONSTRAINT transaction_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.working
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    flight_id bigint NOT NULL,
    staff_id integer NOT NULL,
    CONSTRAINT api_common_working_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_group_id_97559544
    ON public.auth_user_groups(group_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_user_id_6a12ed8b
    ON public.auth_user_groups(user_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_permission_id_1fbb5f2c
    ON public.auth_user_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_user_id_a95ead1b
    ON public.auth_user_user_permissions(user_id);


ALTER TABLE IF EXISTS public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS authtoken_token_user_id_key
    ON public.authtoken_token(user_id);


ALTER TABLE IF EXISTS public.booking
    ADD CONSTRAINT api_common_booking_booking_type_id_93a9f1e4_fk_api_commo FOREIGN KEY (booking_type_id)
    REFERENCES public.booking_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS api_common_booking_booking_type_id_93a9f1e4
    ON public.booking(booking_type_id);


ALTER TABLE IF EXISTS public.booking
    ADD CONSTRAINT api_common_booking_client_id_45d70a25_fk_auth_user_id FOREIGN KEY (client_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS api_common_booking_client_id_45d70a25
    ON public.booking(client_id);


ALTER TABLE IF EXISTS public.booking
    ADD CONSTRAINT api_common_booking_flight_id_73064e8f_fk_api_common_flight_id FOREIGN KEY (flight_id)
    REFERENCES public.flight (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS api_common_booking_flight_id_73064e8f
    ON public.booking(flight_id);


ALTER TABLE IF EXISTS public.cancellation_request
    ADD CONSTRAINT cancellation_request_client_id_56b0cac9_fk_auth_user_id FOREIGN KEY (client_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS cancellation_request_client_id_56b0cac9
    ON public.cancellation_request(client_id);


ALTER TABLE IF EXISTS public.cancellation_request
    ADD CONSTRAINT cancellation_request_flight_id_78dbd6a4_fk_flight_id FOREIGN KEY (flight_id)
    REFERENCES public.flight (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS cancellation_request_flight_id_78dbd6a4
    ON public.cancellation_request(flight_id);


ALTER TABLE IF EXISTS public.client
    ADD CONSTRAINT client_user_id_af1c5063_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS client_user_id_key
    ON public.client(user_id);


ALTER TABLE IF EXISTS public.client_groups
    ADD CONSTRAINT api_common_clientgro_group_id_d4299bf5_fk_api_commo FOREIGN KEY (group_id)
    REFERENCES public."group" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS api_common_clientgroups_group_id_d4299bf5
    ON public.client_groups(group_id);


ALTER TABLE IF EXISTS public.client_groups
    ADD CONSTRAINT api_common_clientgroups_client_id_c7738a60_fk_auth_user_id FOREIGN KEY (client_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS api_common_clientgroups_client_id_c7738a60
    ON public.client_groups(client_id);


ALTER TABLE IF EXISTS public.client_permissions
    ADD CONSTRAINT api_common_clientper_permission_id_34f5ce6d_fk_api_commo FOREIGN KEY (permission_id)
    REFERENCES public.permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS api_common_clientpermissions_permission_id_34f5ce6d
    ON public.client_permissions(permission_id);


ALTER TABLE IF EXISTS public.client_permissions
    ADD CONSTRAINT api_common_clientpermissions_client_id_f3777ad3_fk_auth_user_id FOREIGN KEY (client_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS api_common_clientpermissions_client_id_f3777ad3
    ON public.client_permissions(client_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.flight
    ADD CONSTRAINT api_common_flight_plane_id_c4f423c3_fk_api_common_plane_id FOREIGN KEY (plane_id)
    REFERENCES public.plane (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS api_common_flight_plane_id_c4f423c3
    ON public.flight(plane_id);


ALTER TABLE IF EXISTS public.flight
    ADD CONSTRAINT api_common_flight_track_destination_id_8ddeafff_fk_api_commo FOREIGN KEY (track_destination_id)
    REFERENCES public.track (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS api_common_flight_track_destination_id_8ddeafff
    ON public.flight(track_destination_id);


ALTER TABLE IF EXISTS public.flight
    ADD CONSTRAINT api_common_flight_track_origin_id_b0578178_fk_api_commo FOREIGN KEY (track_origin_id)
    REFERENCES public.track (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS api_common_flight_track_origin_id_b0578178
    ON public.flight(track_origin_id);


ALTER TABLE IF EXISTS public.payment_gateway
    ADD CONSTRAINT payment_gateway_transaction_id_2e728220_fk_transaction_id FOREIGN KEY (transaction_id)
    REFERENCES public.transaction (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS payment_gateway_transaction_id_2e728220
    ON public.payment_gateway(transaction_id);


ALTER TABLE IF EXISTS public.staff
    ADD CONSTRAINT staff_staff_type_id_8a3776c2_fk_staff_type_id FOREIGN KEY (staff_type_id)
    REFERENCES public.staff_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS staff_staff_type_id_8a3776c2
    ON public.staff(staff_type_id);


ALTER TABLE IF EXISTS public.staff
    ADD CONSTRAINT staff_user_id_e6242ba6_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS staff_user_id_key
    ON public.staff(user_id);


ALTER TABLE IF EXISTS public.staff_groups
    ADD CONSTRAINT api_common_staffgroups_group_id_e0190a43_fk_api_common_group_id FOREIGN KEY (group_id)
    REFERENCES public."group" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS api_common_staffgroups_group_id_e0190a43
    ON public.staff_groups(group_id);


ALTER TABLE IF EXISTS public.staff_groups
    ADD CONSTRAINT api_common_staffgroups_staff_id_6f79d9e4_fk_auth_user_id FOREIGN KEY (staff_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS api_common_staffgroups_staff_id_6f79d9e4
    ON public.staff_groups(staff_id);


ALTER TABLE IF EXISTS public.staff_permissions
    ADD CONSTRAINT api_common_staffperm_permission_id_6bc15bf0_fk_api_commo FOREIGN KEY (permission_id)
    REFERENCES public.permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS api_common_staffpermissions_permission_id_6bc15bf0
    ON public.staff_permissions(permission_id);


ALTER TABLE IF EXISTS public.staff_permissions
    ADD CONSTRAINT api_common_staffpermissions_staff_id_e48541ff_fk_auth_user_id FOREIGN KEY (staff_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS api_common_staffpermissions_staff_id_e48541ff
    ON public.staff_permissions(staff_id);


ALTER TABLE IF EXISTS public.track
    ADD CONSTRAINT api_common_track_airport_id_b845c89c_fk_api_common_airport_id FOREIGN KEY (airport_id)
    REFERENCES public.airport (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS api_common_track_airport_id_b845c89c
    ON public.track(airport_id);


ALTER TABLE IF EXISTS public.transaction
    ADD CONSTRAINT transaction_booking_id_7c43ce7e_fk_booking_id FOREIGN KEY (booking_id)
    REFERENCES public.booking (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS transaction_booking_id_7c43ce7e
    ON public.transaction(booking_id);


ALTER TABLE IF EXISTS public.transaction
    ADD CONSTRAINT transaction_client_id_3a47ac76_fk_auth_user_id FOREIGN KEY (client_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS transaction_client_id_3a47ac76
    ON public.transaction(client_id);


ALTER TABLE IF EXISTS public.working
    ADD CONSTRAINT api_common_working_flight_id_7c0c04f3_fk_api_common_flight_id FOREIGN KEY (flight_id)
    REFERENCES public.flight (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS api_common_working_flight_id_7c0c04f3
    ON public.working(flight_id);


ALTER TABLE IF EXISTS public.working
    ADD CONSTRAINT api_common_working_staff_id_ed5c4460_fk_auth_user_id FOREIGN KEY (staff_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS api_common_working_staff_id_ed5c4460
    ON public.working(staff_id);

END;