
CREATE TABLE "app_user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "username" varchar(150) UNIQUE NOT NULL,
  "first_name" varchar(30) NOT NULL,
  "last_name" varchar(30) NOT NULL
);

CREATE TABLE "staff" (
  "id" int PRIMARY KEY,
  "staff_type_id" int
);

CREATE TABLE "staff_type" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar(100) NOT NULL
);

CREATE TABLE "flight" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "flight_number" varchar(10) UNIQUE NOT NULL,
  "departure" timestamptz NOT NULL,
  "arrival" timestamptz NOT NULL,
  "plane_id" int,
  "track_id_origin" int,
  "track_id_destination" int
);

CREATE TABLE "plane" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model" varchar(100) NOT NULL,
  "second_class_capacity" int NOT NULL,
  "first_class_capacity" int NOT NULL
);

CREATE TABLE "booking" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booking_date" timestamptz DEFAULT (current_timestamptz),
  "price" float NOT NULL,
  "booking_type_id" varchar,
  "app_user_id" int,
  "flight_id" int
);

CREATE TABLE "booking_type" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar(30) NOT NULL
);

CREATE TABLE "working" (
  "staff_id" int,
  "flight_id" int
);

CREATE TABLE "airport" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "location" varchar(100) NOT NULL
);

CREATE TABLE "track" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "track_number" varchar(10) NOT NULL,
  "length" int NOT NULL,
  "airport_id" int
);

ALTER TABLE "staff" ADD FOREIGN KEY ("id") REFERENCES "app_user" ("id");

ALTER TABLE "staff" ADD FOREIGN KEY ("staff_type_id") REFERENCES "staff_type" ("id");

ALTER TABLE "flight" ADD FOREIGN KEY ("plane_id") REFERENCES "plane" ("id");

ALTER TABLE "flight" ADD FOREIGN KEY ("track_id_origin") REFERENCES "track" ("id");

ALTER TABLE "flight" ADD FOREIGN KEY ("track_id_destination") REFERENCES "track" ("id");

ALTER TABLE "booking" ADD FOREIGN KEY ("booking_type_id") REFERENCES "booking_type" ("id");

ALTER TABLE "booking" ADD FOREIGN KEY ("app_user_id") REFERENCES "app_user" ("id");

ALTER TABLE "booking" ADD FOREIGN KEY ("flight_id") REFERENCES "flight" ("id");

ALTER TABLE "working" ADD FOREIGN KEY ("staff_id") REFERENCES "staff" ("id");

ALTER TABLE "working" ADD FOREIGN KEY ("flight_id") REFERENCES "flight" ("id");

ALTER TABLE "track" ADD FOREIGN KEY ("airport_id") REFERENCES "airport" ("id");
