table client {
  id int [pk, increment]
  username varchar(150) [unique, not null]
  email varchar [unique, not null]
  password varchar(255) [not null]
  first_name varchar(30) [not null]
  last_name varchar(30) [not null]
  is_staff bool
  is_superuser bool
}

table staff {
  id int [pk, increment]
  username varchar(150) [unique, not null]
  email varchar [unique, not null]
  password varchar(255) [not null]
  is_staff bool
  is_superuser bool
  staff_type_id int [ref: > staff_type.id]
}

Table staff_type {
  id int [pk, increment]
  type varchar(100) [not null]
}

table group {
  id int [pk, increment]
  name varchar
}

table client_groups {
  client_id int [ref: > client.id]
  group_id int [ref: > group.id]
}

table staff_groups {
  staff_id int [ref: > staff.id]
  group_id int [ref: > group.id]
}

table permission {
  id int [pk, increment]
  name varchar
}

table client_permissions {
  client_id int [ref: > client.id]
  permission_id int [ref: > permission.id]
}

table staff_permissions {
  staff_id int [ref: > staff.id]
  permission_id int [ref: > permission.id]
}

table flight {
  id int [pk, increment]
  flight_number varchar(10) [not null, unique]
  departure timestamptz [not null]
  arrival timestamptz [not null]
  plane_id int [ref: > plane.id]
  track_id_origin int [ref: > track.id]
  track_id_destination int [ref: > track.id]
}

table plane {
  id int [pk, increment]
  model varchar(100) [not null]
  second_class_capacity int [not null]
  first_class_capacity int [not null]
}

table booking {
  id int [pk, increment]
  booking_date timestamptz [default: `CURRENT_TIMESTAMP`]
  price float [not null]
  booking_type_id varchar [ref: > booking_type.id]
  app_user_id int [ref: > client.id]
  flight_id int [ref: > flight.id]
}

table booking_type {
  id int [pk, increment]
  type varchar(30) [not null]
}

table working {
  staff_id int [ref: > staff.id]
  flight_id int [ref: > flight.id]
}

table airport {
  id int [pk, increment]
  name varchar(100) [not null]
  location varchar(100) [not null]
}

table track {
  id int [pk, increment]
  track_number varchar(10) [not null]
  length int [not null]
  airport_id int [ref: > airport.id]
}