table client {
  id int [pk, increment]
  user varchar(150) [unique, not null]
  is_staff bool
  is_superuser bool
}

table staff {
  id int [pk, increment]
  user varchar(150) [unique, not null]
  is_staff bool
  is_superuser bool
  staff_type int [ref: > staff_type.id]
}

Table staff_type {
  id int [pk, increment]
  type varchar(100) [not null]
}

table group {
  id int [pk, increment]
  name varchar
}

table client_groups {
  client int [ref: > client.id]
  group int [ref: > group.id]
}

table staff_groups {
  staff int [ref: > staff.id]
  group int [ref: > group.id]
}

table permission {
  id int [pk, increment]
  name varchar
}

table client_permissions {
  client int [ref: > client.id]
  permission int [ref: > permission.id]
}

table staff_permissions {
  staff int [ref: > staff.id]
  permission int [ref: > permission.id]
}

table flight {
  id int [pk, increment]
  flight_number varchar(10) [not null, unique]
  departure timestamptz [not null]
  arrival timestamptz [not null]
  plane int [ref: > plane.id]
  track_origin int [ref: > track.id]
  track_destination int [ref: > track.id]
}

table plane {
  id int [pk, increment]
  model varchar(100) [not null]
  second_class_capacity int [not null]
  first_class_capacity int [not null]
}

table booking {
  id int [pk, increment]
  booking_date timestamptz [default: `CURRENT_TIMESTAMP`]
  price float [not null]
  booking_type int [ref: > booking_type.id]
  client int [ref: > client.id]
  flight int [ref: > flight.id]
}

table booking_type {
  id int [pk, increment]
  type varchar(30) [not null]
}

table working {
  staff int [ref: > staff.id]
  flight int [ref: > flight.id]
}

table airport {
  id int [pk, increment]
  name varchar(100) [not null]
  location varchar(100) [not null]
}

table track {
  id int [pk, increment]
  track_number varchar(10) [not null]
  length int [not null]
  airport int [ref: > airport.id]
}