--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3 (Debian 16.3-1.pgdg120+1)
-- Dumped by pg_dump version 16.3 (Debian 16.3-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: airport; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.airport (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    location character varying(100) NOT NULL
);


ALTER TABLE public.airport OWNER TO app;

--
-- Name: api_common_airport_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.airport ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_common_airport_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: booking; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.booking (
    id bigint NOT NULL,
    booking_date timestamp with time zone NOT NULL,
    client_id integer NOT NULL,
    booking_type_id bigint NOT NULL,
    flight_id bigint NOT NULL
);


ALTER TABLE public.booking OWNER TO app;

--
-- Name: api_common_booking_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.booking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_common_booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: booking_type; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.booking_type (
    id bigint NOT NULL,
    type character varying(30) NOT NULL,
    price double precision
);


ALTER TABLE public.booking_type OWNER TO app;

--
-- Name: api_common_bookingtype_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.booking_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_common_bookingtype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client_groups; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.client_groups (
    id bigint NOT NULL,
    client_id integer NOT NULL,
    group_id bigint NOT NULL
);


ALTER TABLE public.client_groups OWNER TO app;

--
-- Name: api_common_clientgroups_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.client_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_common_clientgroups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client_permissions; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.client_permissions (
    id bigint NOT NULL,
    client_id integer NOT NULL,
    permission_id bigint NOT NULL
);


ALTER TABLE public.client_permissions OWNER TO app;

--
-- Name: api_common_clientpermissions_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.client_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_common_clientpermissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flight; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.flight (
    id bigint NOT NULL,
    flight_number character varying(10) NOT NULL,
    departure timestamp with time zone NOT NULL,
    arrival timestamp with time zone NOT NULL,
    plane_id bigint NOT NULL,
    track_destination_id bigint NOT NULL,
    track_origin_id bigint NOT NULL
);


ALTER TABLE public.flight OWNER TO app;

--
-- Name: api_common_flight_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.flight ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_common_flight_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: group; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public."group" (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public."group" OWNER TO app;

--
-- Name: api_common_group_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public."group" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_common_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permission; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.permission (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.permission OWNER TO app;

--
-- Name: api_common_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_common_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plane; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.plane (
    id bigint NOT NULL,
    model character varying(100) NOT NULL,
    second_class_capacity integer NOT NULL,
    first_class_capacity integer NOT NULL
);


ALTER TABLE public.plane OWNER TO app;

--
-- Name: api_common_plane_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.plane ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_common_plane_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: staff_groups; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.staff_groups (
    id bigint NOT NULL,
    group_id bigint NOT NULL,
    staff_id integer NOT NULL
);


ALTER TABLE public.staff_groups OWNER TO app;

--
-- Name: api_common_staffgroups_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.staff_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_common_staffgroups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: staff_permissions; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.staff_permissions (
    id bigint NOT NULL,
    permission_id bigint NOT NULL,
    staff_id integer NOT NULL
);


ALTER TABLE public.staff_permissions OWNER TO app;

--
-- Name: api_common_staffpermissions_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.staff_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_common_staffpermissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: staff_type; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.staff_type (
    id bigint NOT NULL,
    type character varying(100) NOT NULL
);


ALTER TABLE public.staff_type OWNER TO app;

--
-- Name: api_common_stafftype_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.staff_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_common_stafftype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: track; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.track (
    id bigint NOT NULL,
    track_number character varying(10) NOT NULL,
    length integer NOT NULL,
    airport_id bigint NOT NULL
);


ALTER TABLE public.track OWNER TO app;

--
-- Name: api_common_track_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.track ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_common_track_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: working; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.working (
    id bigint NOT NULL,
    flight_id bigint NOT NULL,
    staff_id integer NOT NULL
);


ALTER TABLE public.working OWNER TO app;

--
-- Name: api_common_working_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.working ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_common_working_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO app;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO app;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO app;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO app;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO app;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO app;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO app;

--
-- Name: cancellation_request; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.cancellation_request (
    id bigint NOT NULL,
    request_date timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL,
    reason text,
    client_id integer NOT NULL,
    flight_id bigint NOT NULL
);


ALTER TABLE public.cancellation_request OWNER TO app;

--
-- Name: cancellation_request_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.cancellation_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cancellation_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.client (
    id bigint NOT NULL,
    is_staff boolean NOT NULL,
    is_superuser boolean NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.client OWNER TO app;

--
-- Name: client_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO app;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO app;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO app;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO app;

--
-- Name: payment_gateway; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.payment_gateway (
    id bigint NOT NULL,
    gateway_response text NOT NULL,
    status character varying(20) NOT NULL,
    processed_at timestamp with time zone NOT NULL,
    transaction_id bigint NOT NULL
);


ALTER TABLE public.payment_gateway OWNER TO app;

--
-- Name: payment_gateway_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.payment_gateway ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_gateway_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: staff; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.staff (
    id bigint NOT NULL,
    is_staff boolean NOT NULL,
    is_superuser boolean NOT NULL,
    staff_type_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.staff OWNER TO app;

--
-- Name: staff_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.staff ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.staff_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaction; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.transaction (
    id bigint NOT NULL,
    amount double precision NOT NULL,
    transaction_date timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL,
    booking_id bigint,
    client_id integer NOT NULL
);


ALTER TABLE public.transaction OWNER TO app;

--
-- Name: transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: airport api_common_airport_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.airport
    ADD CONSTRAINT api_common_airport_pkey PRIMARY KEY (id);


--
-- Name: booking api_common_booking_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT api_common_booking_pkey PRIMARY KEY (id);


--
-- Name: booking_type api_common_bookingtype_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.booking_type
    ADD CONSTRAINT api_common_bookingtype_pkey PRIMARY KEY (id);


--
-- Name: client_groups api_common_clientgroups_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.client_groups
    ADD CONSTRAINT api_common_clientgroups_pkey PRIMARY KEY (id);


--
-- Name: client_permissions api_common_clientpermissions_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.client_permissions
    ADD CONSTRAINT api_common_clientpermissions_pkey PRIMARY KEY (id);


--
-- Name: flight api_common_flight_flight_number_key; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.flight
    ADD CONSTRAINT api_common_flight_flight_number_key UNIQUE (flight_number);


--
-- Name: flight api_common_flight_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.flight
    ADD CONSTRAINT api_common_flight_pkey PRIMARY KEY (id);


--
-- Name: group api_common_group_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public."group"
    ADD CONSTRAINT api_common_group_pkey PRIMARY KEY (id);


--
-- Name: permission api_common_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT api_common_permission_pkey PRIMARY KEY (id);


--
-- Name: plane api_common_plane_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.plane
    ADD CONSTRAINT api_common_plane_pkey PRIMARY KEY (id);


--
-- Name: staff_groups api_common_staffgroups_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.staff_groups
    ADD CONSTRAINT api_common_staffgroups_pkey PRIMARY KEY (id);


--
-- Name: staff_permissions api_common_staffpermissions_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.staff_permissions
    ADD CONSTRAINT api_common_staffpermissions_pkey PRIMARY KEY (id);


--
-- Name: staff_type api_common_stafftype_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.staff_type
    ADD CONSTRAINT api_common_stafftype_pkey PRIMARY KEY (id);


--
-- Name: track api_common_track_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.track
    ADD CONSTRAINT api_common_track_pkey PRIMARY KEY (id);


--
-- Name: working api_common_working_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.working
    ADD CONSTRAINT api_common_working_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: cancellation_request cancellation_request_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.cancellation_request
    ADD CONSTRAINT cancellation_request_pkey PRIMARY KEY (id);


--
-- Name: client client_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (id);


--
-- Name: client client_user_id_key; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: payment_gateway payment_gateway_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.payment_gateway
    ADD CONSTRAINT payment_gateway_pkey PRIMARY KEY (id);


--
-- Name: staff staff_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.staff
    ADD CONSTRAINT staff_pkey PRIMARY KEY (id);


--
-- Name: staff staff_user_id_key; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.staff
    ADD CONSTRAINT staff_user_id_key UNIQUE (user_id);


--
-- Name: transaction transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_pkey PRIMARY KEY (id);


--
-- Name: api_common_booking_booking_type_id_93a9f1e4; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX api_common_booking_booking_type_id_93a9f1e4 ON public.booking USING btree (booking_type_id);


--
-- Name: api_common_booking_client_id_45d70a25; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX api_common_booking_client_id_45d70a25 ON public.booking USING btree (client_id);


--
-- Name: api_common_booking_flight_id_73064e8f; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX api_common_booking_flight_id_73064e8f ON public.booking USING btree (flight_id);


--
-- Name: api_common_clientgroups_client_id_c7738a60; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX api_common_clientgroups_client_id_c7738a60 ON public.client_groups USING btree (client_id);


--
-- Name: api_common_clientgroups_group_id_d4299bf5; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX api_common_clientgroups_group_id_d4299bf5 ON public.client_groups USING btree (group_id);


--
-- Name: api_common_clientpermissions_client_id_f3777ad3; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX api_common_clientpermissions_client_id_f3777ad3 ON public.client_permissions USING btree (client_id);


--
-- Name: api_common_clientpermissions_permission_id_34f5ce6d; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX api_common_clientpermissions_permission_id_34f5ce6d ON public.client_permissions USING btree (permission_id);


--
-- Name: api_common_flight_flight_number_6741596a_like; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX api_common_flight_flight_number_6741596a_like ON public.flight USING btree (flight_number varchar_pattern_ops);


--
-- Name: api_common_flight_plane_id_c4f423c3; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX api_common_flight_plane_id_c4f423c3 ON public.flight USING btree (plane_id);


--
-- Name: api_common_flight_track_destination_id_8ddeafff; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX api_common_flight_track_destination_id_8ddeafff ON public.flight USING btree (track_destination_id);


--
-- Name: api_common_flight_track_origin_id_b0578178; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX api_common_flight_track_origin_id_b0578178 ON public.flight USING btree (track_origin_id);


--
-- Name: api_common_staffgroups_group_id_e0190a43; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX api_common_staffgroups_group_id_e0190a43 ON public.staff_groups USING btree (group_id);


--
-- Name: api_common_staffgroups_staff_id_6f79d9e4; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX api_common_staffgroups_staff_id_6f79d9e4 ON public.staff_groups USING btree (staff_id);


--
-- Name: api_common_staffpermissions_permission_id_6bc15bf0; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX api_common_staffpermissions_permission_id_6bc15bf0 ON public.staff_permissions USING btree (permission_id);


--
-- Name: api_common_staffpermissions_staff_id_e48541ff; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX api_common_staffpermissions_staff_id_e48541ff ON public.staff_permissions USING btree (staff_id);


--
-- Name: api_common_track_airport_id_b845c89c; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX api_common_track_airport_id_b845c89c ON public.track USING btree (airport_id);


--
-- Name: api_common_working_flight_id_7c0c04f3; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX api_common_working_flight_id_7c0c04f3 ON public.working USING btree (flight_id);


--
-- Name: api_common_working_staff_id_ed5c4460; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX api_common_working_staff_id_ed5c4460 ON public.working USING btree (staff_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: cancellation_request_client_id_56b0cac9; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX cancellation_request_client_id_56b0cac9 ON public.cancellation_request USING btree (client_id);


--
-- Name: cancellation_request_flight_id_78dbd6a4; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX cancellation_request_flight_id_78dbd6a4 ON public.cancellation_request USING btree (flight_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: payment_gateway_transaction_id_2e728220; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX payment_gateway_transaction_id_2e728220 ON public.payment_gateway USING btree (transaction_id);


--
-- Name: staff_staff_type_id_8a3776c2; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX staff_staff_type_id_8a3776c2 ON public.staff USING btree (staff_type_id);


--
-- Name: transaction_booking_id_7c43ce7e; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX transaction_booking_id_7c43ce7e ON public.transaction USING btree (booking_id);


--
-- Name: transaction_client_id_3a47ac76; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX transaction_client_id_3a47ac76 ON public.transaction USING btree (client_id);


--
-- Name: booking api_common_booking_booking_type_id_93a9f1e4_fk_api_commo; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT api_common_booking_booking_type_id_93a9f1e4_fk_api_commo FOREIGN KEY (booking_type_id) REFERENCES public.booking_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: booking api_common_booking_client_id_45d70a25_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT api_common_booking_client_id_45d70a25_fk_auth_user_id FOREIGN KEY (client_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: booking api_common_booking_flight_id_73064e8f_fk_api_common_flight_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT api_common_booking_flight_id_73064e8f_fk_api_common_flight_id FOREIGN KEY (flight_id) REFERENCES public.flight(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: client_groups api_common_clientgro_group_id_d4299bf5_fk_api_commo; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.client_groups
    ADD CONSTRAINT api_common_clientgro_group_id_d4299bf5_fk_api_commo FOREIGN KEY (group_id) REFERENCES public."group"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: client_groups api_common_clientgroups_client_id_c7738a60_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.client_groups
    ADD CONSTRAINT api_common_clientgroups_client_id_c7738a60_fk_auth_user_id FOREIGN KEY (client_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: client_permissions api_common_clientper_permission_id_34f5ce6d_fk_api_commo; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.client_permissions
    ADD CONSTRAINT api_common_clientper_permission_id_34f5ce6d_fk_api_commo FOREIGN KEY (permission_id) REFERENCES public.permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: client_permissions api_common_clientpermissions_client_id_f3777ad3_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.client_permissions
    ADD CONSTRAINT api_common_clientpermissions_client_id_f3777ad3_fk_auth_user_id FOREIGN KEY (client_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: flight api_common_flight_plane_id_c4f423c3_fk_api_common_plane_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.flight
    ADD CONSTRAINT api_common_flight_plane_id_c4f423c3_fk_api_common_plane_id FOREIGN KEY (plane_id) REFERENCES public.plane(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: flight api_common_flight_track_destination_id_8ddeafff_fk_api_commo; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.flight
    ADD CONSTRAINT api_common_flight_track_destination_id_8ddeafff_fk_api_commo FOREIGN KEY (track_destination_id) REFERENCES public.track(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: flight api_common_flight_track_origin_id_b0578178_fk_api_commo; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.flight
    ADD CONSTRAINT api_common_flight_track_origin_id_b0578178_fk_api_commo FOREIGN KEY (track_origin_id) REFERENCES public.track(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: staff_groups api_common_staffgroups_group_id_e0190a43_fk_api_common_group_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.staff_groups
    ADD CONSTRAINT api_common_staffgroups_group_id_e0190a43_fk_api_common_group_id FOREIGN KEY (group_id) REFERENCES public."group"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: staff_groups api_common_staffgroups_staff_id_6f79d9e4_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.staff_groups
    ADD CONSTRAINT api_common_staffgroups_staff_id_6f79d9e4_fk_auth_user_id FOREIGN KEY (staff_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: staff_permissions api_common_staffperm_permission_id_6bc15bf0_fk_api_commo; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.staff_permissions
    ADD CONSTRAINT api_common_staffperm_permission_id_6bc15bf0_fk_api_commo FOREIGN KEY (permission_id) REFERENCES public.permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: staff_permissions api_common_staffpermissions_staff_id_e48541ff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.staff_permissions
    ADD CONSTRAINT api_common_staffpermissions_staff_id_e48541ff_fk_auth_user_id FOREIGN KEY (staff_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: track api_common_track_airport_id_b845c89c_fk_api_common_airport_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.track
    ADD CONSTRAINT api_common_track_airport_id_b845c89c_fk_api_common_airport_id FOREIGN KEY (airport_id) REFERENCES public.airport(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: working api_common_working_flight_id_7c0c04f3_fk_api_common_flight_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.working
    ADD CONSTRAINT api_common_working_flight_id_7c0c04f3_fk_api_common_flight_id FOREIGN KEY (flight_id) REFERENCES public.flight(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: working api_common_working_staff_id_ed5c4460_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.working
    ADD CONSTRAINT api_common_working_staff_id_ed5c4460_fk_auth_user_id FOREIGN KEY (staff_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cancellation_request cancellation_request_client_id_56b0cac9_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.cancellation_request
    ADD CONSTRAINT cancellation_request_client_id_56b0cac9_fk_auth_user_id FOREIGN KEY (client_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cancellation_request cancellation_request_flight_id_78dbd6a4_fk_flight_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.cancellation_request
    ADD CONSTRAINT cancellation_request_flight_id_78dbd6a4_fk_flight_id FOREIGN KEY (flight_id) REFERENCES public.flight(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: client client_user_id_af1c5063_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_user_id_af1c5063_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payment_gateway payment_gateway_transaction_id_2e728220_fk_transaction_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.payment_gateway
    ADD CONSTRAINT payment_gateway_transaction_id_2e728220_fk_transaction_id FOREIGN KEY (transaction_id) REFERENCES public.transaction(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: staff staff_staff_type_id_8a3776c2_fk_staff_type_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.staff
    ADD CONSTRAINT staff_staff_type_id_8a3776c2_fk_staff_type_id FOREIGN KEY (staff_type_id) REFERENCES public.staff_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: staff staff_user_id_e6242ba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.staff
    ADD CONSTRAINT staff_user_id_e6242ba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transaction transaction_booking_id_7c43ce7e_fk_booking_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_booking_id_7c43ce7e_fk_booking_id FOREIGN KEY (booking_id) REFERENCES public.booking(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transaction transaction_client_id_3a47ac76_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_client_id_3a47ac76_fk_auth_user_id FOREIGN KEY (client_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

